### ISSUE TITLE
Feat: 예외처리 기능 셋팅

### ISSUE THREAD

**Issue by kaley0421** [LINKIT-dev/LINKIT_server#12]
## 🫶🏻 Description
- 예외처리 기능을 추가합니다.

## 🧑🏻‍💻 Tasks
- [x] `ErrorCode` enum 추가
- [x] `ErrorResponse` class 추가
- [x] `BusinessException` class 추가
- [x] `GlobalExceptionHandler` 추가

**Comment by SeungHo0422** [comment]
@kaley0421 통화할 때 나눴던 Exception fix issue 관련해서 이슈 남깁니다.
🧑🏻‍💻 Tasks
`BusinessException` 내의 CommonErrorCode 뿐만 아니라, `ErrorResponse` 속 모든 CommonErrorCode를 ErrorCode로 수정해야 할 것 같아요. 코드들이 조금씩 연결되어 있다 보니 그렇습니다.
아니면 CommonErrorCode 뿐만 아니라, ErrorCode에 대한 생성자 오버로딩을 구현하는 것도 방법일 것 같군요
